import os
from pathlib import Path

STATE_DIR = Path(os.getenv("HTBMC_STATE_DIR", "./state")).resolve()
TARGETS_DIR = STATE_DIR / "targets"
SETTINGS_DIR = STATE_DIR / "settings"
RUNTIME_SETTINGS_PATH = SETTINGS_DIR / "runtime.json"
PLANNER_LOG_PATH = STATE_DIR / "logs" / "llm_planner.jsonl"
LLM_PROMPTS_LOG_PATH = STATE_DIR / "logs" / "llm_prompts.jsonl"

NMAP_BIN = os.getenv("HTBMC_NMAP_BIN", "nmap")
SCAN_TIMEOUT_SECONDS = int(os.getenv("HTBMC_SCAN_TIMEOUT_SECONDS", "1200"))
ACTION_TIMEOUT_SECONDS = int(os.getenv("HTBMC_ACTION_TIMEOUT_SECONDS", "180"))
OLLAMA_TAILSCALE_HOST = os.getenv("OLLAMA_TAILSCALE_HOST", "").strip()
OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "").strip()
OLLAMA_TIMEOUT_SECONDS = float(os.getenv("HTBMC_OLLAMA_TIMEOUT_SECONDS", "5"))
PLANNER_INTERVAL_SECONDS = float(os.getenv("HTBMC_PLANNER_INTERVAL_SECONDS", "20"))
PLANNER_MAX_PENDING_ACTIONS = int(os.getenv("HTBMC_PLANNER_MAX_PENDING_ACTIONS", "6"))
PLANNER_GLOBAL_RPM = max(1, int(os.getenv("HTBMC_PLANNER_GLOBAL_RPM", "30")))
PLANNER_INFLIGHT_LIMIT = max(1, int(os.getenv("HTBMC_PLANNER_INFLIGHT_LIMIT", "2")))
PLANNER_TARGET_COOLDOWN_SECONDS = max(0.0, float(os.getenv("HTBMC_PLANNER_TARGET_COOLDOWN_SECONDS", "5")))
PLANNER_MAX_UNRESOLVED_ACTIONS = max(1, int(os.getenv("HTBMC_PLANNER_MAX_UNRESOLVED_ACTIONS", "8")))
STATE_SCHEMA_VERSION = 2
LIVE_OUTPUT_TAIL_LIMIT = 12000
LIVE_EVENT_LIMIT = 120
PROCESS_STOP_WAIT_SECONDS = 5
SHELL_TOKEN_TTL_SECONDS = 120
